In [1]:
from array import *

In [5]:
vals = array('i', [5,9,6,3,8])

In [7]:
newArr = array(vals.typecode, (a*a for a in vals))
for i in range(len(newArr)):
    print(newArr[i])

25
81
36
9
64


In [8]:
while i < len(newArr):
    print(newArr[i])
    i += 1

64


In [11]:
# Array from user
arr = array('i', [])

n = int(input('Length of Array: '))

for i in range(n):
    x = int(input('Enter element: '))
    arr.append(x)

print(f'Array is  {arr}')

val = int(input('Element to search: '))
for i in range(len(arr)):
    if arr[i] == val:
        print(f'Index for element {val} via loop: {i}')

print(f'Index for element {val} via loop: {arr.index(val)}')

Length of Array:  3
Enter element:  12
Enter element:  56
Enter element:  89


Array is  array('i', [12, 56, 89])


Element to search:  56


Index for element 56 via loop: 1
Index for element 56 via loop: 1


# Matrices - Tutorial 1

In [3]:
from numpy import *

In [7]:
a = array([
    [1,2,3],
    [4,5,6]
])

print('Matriz: ',a)
print('Dimension: ',a.ndim)
print('Shape: ',a.shape)
print('Size: ',a.size)

Matriz:  [[1 2 3]
 [4 5 6]]
Dimension:  2
Shape:  (2, 3)
Size:  6


In [8]:
# 2D to 1D
a2 = a.flatten()
print('Flatten: ',a2)

Flatten:  [1 2 3 4 5 6]


In [10]:
# 1D to 2D/3D
a3 = a2.reshape(3,2)
print('Reshaped: ', a3)

Reshaped:  [[1 2]
 [3 4]
 [5 6]]


In [13]:
m = matrix[a]
print('Matrix 1: ', m)

Matrix 1:  numpy.matrix[array([[1, 2, 3],
       [4, 5, 6]])]


In [16]:
m1 = matrix('1 2 3 4 ; 5 6 7 8 ')
print('Matrix 2: ', m1)

Matrix 2:  [[1 2 3 4]
 [5 6 7 8]]


In [18]:
m3 = matrix('1 2 12; 3 4 2;  5 6 6; 7 8 0')
print('Matrix 3: ', m3)

Matrix 3:  [[ 1  2 12]
 [ 3  4  2]
 [ 5  6  6]
 [ 7  8  0]]


In [24]:
print('Diagonal :', diagonal(m3))
print('Max :', m3.max())

Diagonal : [1 4 6]
Max : 12


In [26]:
m4 = matrix('1 2 3 ; 4 5 6; 7 8 9')
m5 = matrix('9 8 7 ; 6 5 4 ; 3 2 1')
print('Sum :', m4 + m5)
print('Multiplication :', m4 * m5)

Sum : [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication : [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Matrices - Tutorial 2

In [28]:
A1 = array([
    [2,5,7],
    [3,4,8],
    [8,4,5]
])

A2 = array([
    [5,5,8],
    [8,6,3],
    [5,9,7]
])

In [30]:
# Addition
print('Addition : ', A1 + A2)
# Subtraction
print('Subtraction : ', A1 - A2)

Addition :  [[ 7 10 15]
 [11 10 11]
 [13 13 12]]
Subtraction :  [[-3  0 -1]
 [-5 -2  5]
 [ 3 -5 -2]]


In [31]:
# Multiplication
print('Multiplication 1 : ', A1.dot(A2))
print('Multiplication 2 : ', matmul(A1, A2))
print('Multiplication 3 : ', A1 @ A2)

Multiplication 1 :  [[ 85 103  80]
 [ 87 111  92]
 [ 97 109 111]]
Multiplication 2 :  [[ 85 103  80]
 [ 87 111  92]
 [ 97 109 111]]
Multiplication 3 :  [[ 85 103  80]
 [ 87 111  92]
 [ 97 109 111]]


In [32]:
# Element Wise Multiplication
print('Element Wise Multiplication : ', A1 * A2)

Element Wise Multiplication :  [[10 25 56]
 [24 24 24]
 [40 36 35]]


In [33]:
# Eigen Values
print('Eigen Values : ', linalg.eigvals(A1))

Eigen Values :  [15.52336966+0.j         -2.26168483+0.32050117j -2.26168483-0.32050117j]


In [34]:
# Inverse of Matrix
print('Inverse of A1 : ', linalg.inv(A1))

Inverse of A1 :  [[-0.14814815  0.03703704  0.14814815]
 [ 0.60493827 -0.56790123  0.0617284 ]
 [-0.24691358  0.39506173 -0.08641975]]


# Matrix multiplication without numpy

1. Number of columns in A1 should be equal to number of columns in A2.
2. Initialize a result matrix with 0s, where the size of the result will be determined on the number of rows of A1 and number of columns of A2.
3. Three loops: Outer loop - Goes through each row of A1.
                Middle loop - Goes through each column of A2.
                Inner loop - To calculate the values of the result matrix
4. Multiply the corresponding elements from A1 row and A2 column, then add them up.

In [37]:
result = [[0] * len(A2[0]) for _ in range(len(A1))]
print(result)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [38]:
def matrix_mul(a1, a2):
    result = [[0] * len(a2[0]) for _ in range(len(a1))]

    for i in range(len(a1)):
        for j in range(len(a2[0])):
            for k in range(len(a1)):
                result[i][j] += a1[i][k] * a2[k][j]

    return result

In [43]:
a1 = array([[3,4,7],[7,8,8]])
a2 = array([[1,2,5],[3,4,6]])

print('Matrix Multiplication without numpy : ')
print(matrix_mul(a1, a2))

Matrix Multiplication without numpy : 
[[15, 22, 39], [31, 46, 83]]


# Matrix Transpose without numpy

1. The shape of the result matrix will change from row * column to column * row.
2. Initialize result matrix with zeroes.
3. Two loops: Outer loop - Iterate over rows.
              Inner loop - Iterate over columns.
4. Fill the result matrix.

In [47]:
def mat_transpose(a1):
    rows = len(a1)
    cols = len(a1[0])
    result = [[0] * rows for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            result[j][i] = a1[i][j]
    return result

In [48]:
print('Matrix transpose without numpy : ')
print(mat_transpose(a1))

Matrix transpose without numpy : 
[[3, 7], [4, 8], [7, 8]]


# Practice Questions

## Basic

In [58]:
import random

#Create a 3x3 matrix and fill it with random integers between 1 and 10.

m1 = array([[random.random() for _ in range(3)] for _ in range(3)])
print('Create a 3x3 matrix and fill it with random integers between 1 and 10.')
print(m1)

#Create a 4x4 matrix with all elements set to zero.

m2 = array([[0] * 4 for _ in range(4)])
print('Create a 4x4 matrix with all elements set to zero.')
print(m2)

#Create an identity matrix of size 5x5.

def identity_mat(n):
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        result[i][i] = 1
    return result

print('Create an identity matrix of size 5x5.')
print(identity_mat(5))

Create a 3x3 matrix and fill it with random integers between 1 and 10.
[[0.75288905 0.08486628 0.67103026]
 [0.5165005  0.81059631 0.04578095]
 [0.72288411 0.29491835 0.67536375]]
Create a 4x4 matrix with all elements set to zero.
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Create an identity matrix of size 5x5.
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [61]:
# Write a function to add two matrices of the same size.

def mat_addition(m1, m2):
    if m1.size == m2.size:
        return m1 + m2
    else:
        return 'Different Sizes'

a1 = array([[1,2,3],[4,5,6]])
a2 = array([[3,6,1],[6,4,9]])
a3 = array([[3,5],[7,9]])
print('Matrix Addition: ', mat_addition(a1, a2))
print('Matrix Addition: ', mat_addition(a1, a3))

Matrix Addition:  [[ 4  8  4]
 [10  9 15]]
Matrix Addition:  Different Sizes


In [65]:
# Write a function to compute the transpose of a matrix.

def transpose_mat(m):
    rows = len(m)
    cols = len(m[0])
    result = [[0] * rows for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            result[j][i] = m[i][j]
    return result

print('Transpose: ', transpose_mat(a1))

Transpose:  [[1, 4], [2, 5], [3, 6]]


In [66]:
# Implement scalar multiplication for a matrix. (Multiply all elements of a matrix by a constant scalar).
scalar_result = 4 * a1
print('Implement scalar multiplication for a matrix. (Multiply all elements of a matrix by a constant scalar). : ',scalar_result)

Implement scalar multiplication for a matrix. (Multiply all elements of a matrix by a constant scalar). :  [[ 4  8 12]
 [16 20 24]]


In [71]:
# Write a function to perform matrix multiplication

def mat_mul(a1, a2):
    result = [[0] * len(a2[0]) for _ in range(len(a1))]
    for i in range(len(a1)):
        for j in range(len(a2[0])):
            for k in range(len(a2)):
                result[i][j] += a1[i][k] * a2[k][j]
    return result

print(f'a1 : {a1}, a2 : {a2}')
print('Write a function to perform matrix multiplication: ',mat_mul(a1, a2))

a1 : [[1 2 3]
 [4 5 6]], a2 : [[3 6 1]
 [6 4 9]]
Write a function to perform matrix multiplication:  [[15, 14, 19], [42, 44, 49]]


In [73]:
# Write a function to compute the inverse of a 2x2 matrix using the formula for the inverse.
def mat_inverse(m):
    return linalg.inv(m)

print('Write a function to compute the inverse of a 2x2 matrix using the formula for the inverse : ', mat_inverse(a3))

Write a function to compute the inverse of a 2x2 matrix using the formula for the inverse :  [[-1.125  0.625]
 [ 0.875 -0.375]]


In [75]:
# Write a function to calculate the determinant of a 2x2 matrix.

def mat_deter(m):
    a, b = m[0]
    c, d = m[1]
    return (a * d) - (b * c)

print('Write a function to calculate the determinant of a 2x2 matrix : ', mat_deter(a3))

Write a function to calculate the determinant of a 2x2 matrix :  -8
